pub mod config;
pub mod decay;
pub mod decay_schedule;
pub mod engine;
pub mod memory;
pub mod multi_agent;
pub mod persistence;
pub mod personality;
pub mod plutchik;
pub mod prompt;
pub mod rumination;
pub mod vad;

pub use config::{BehaviorConfig, EventConfig};
pub use decay_schedule::DecaySchedule;
pub use engine::Engine;
pub use memory::EmotionalMemory;
pub use personality::OceanProfile;
pub use plutchik::{classify_plutchik, PlutchikResult, PlutchikState};
pub use rumination::RuminationEntry;
pub use vad::VadState;
